config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  get "password_resets/new"
  get "password_resets/edit"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/notfound", to: "static_pages#notfound"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed
        .paginate(page: params[:page], per_page: Settings.common.per_page)
    end
  end

  def help; end

  def about; end

  def contact; end

  def notfound; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, t(".title_message") %>

<h1> <%= t ".title_message" %> </h1>
<p>
  <%= t(".about_page_message",
    link_to_tutorial: link_to(t("static_pages.help.tutorial_message"),
    "https://www.railstutorial.org/help"),
    link_to_tutorial_book: link_to(t(".book_message"),
    "https://www.railstutorial.org/book"),
    link_to_screencast: link_to(t(".screencast_message"),
    "http://screencasts.railstutorial.org/"),
    ).html_safe %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title_message") %>

<h1><%= t(".title_message") %></h1>
<p>
  <%= t(".contact_page_message",
    link_to_contact: link_to(t(".contact_message"), "https://www.railstutorial.org/contact")).html_safe %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title_message") %>

<h1> <%= t ".title_message" %> </h1>
<p>
  <%= t(".help_page_message",
    link_to_tutorial_help: link_to(t(".help_message"),"https://www.railstutorial.org/help"),
    link_to_tutorial_book: link_to(t(".tutorial_message"),
    "https://www.railstutorial.org/book")).html_safe %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".title_message") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= t ".micropost_feed" %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1> <%= t ".title_message" %> </h1>
  <p>
    <%= t(".home_page_message",
      link_to_tutorial: link_to(t(".rubyonrails_message"),
      "https://www.railstutorial.org/")).html_safe %>
  </p>
  <%= link_to t(".signup_link"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: t(".alt_image_rails")),
  "http://rubyonrails.org/" %>
<% end %>

app/views/static_pages/notfound.html.erb
<h1><%= flash[:danger] if flash[:danger] %></h1>