config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  
  get "password_resets/new"
  get "password_resets/edit"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/notfound", to: "static_pages#notfound"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   <%= t(".description_book",
    link_to_tutorial: link_to(t(".tutorial_book_name"), "https://www.railstutorial.org/"),
    link_to_author_tutorial: link_to(t(".tutorial_author_name"), "http://www.michaelhartl.com/")).html_safe %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".common.about"), about_path %></li>
      <li><%= link_to t(".common.contact"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t(".common.news") %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".common.name_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".common.home"), root_path %></li>
        <li><%= link_to t(".common.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <%= link_to t(".account"), class: "dropdown-toggle", data: { toggle: "dropdown" } do %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".account"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login_"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "i18n" %>
    <script type="text/javascript">
     I18n.defaultLocale = "<%= I18n.default_locale %>";
     I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">  
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>